# Generated by Django 3.0.7 on 2020-06-28 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('gid', models.IntegerField(primary_key=True, serialize=False)),
                ('genre', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'genre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('mid', models.IntegerField(primary_key=True, serialize=False)),
                ('titlename', models.CharField(db_column='titleName', max_length=100)),
                ('releasedate', models.DateField(db_column='releaseDate')),
                ('imdburl', models.CharField(db_column='IMDbUrl', max_length=150)),
            ],
            options={
                'db_table': 'movie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=2)),
                ('occupation', models.CharField(max_length=15)),
                ('zipcode', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=15)),
                ('occupation', models.CharField(max_length=15)),
                ('min_rating', models.FloatField()),
                ('max_rating', models.FloatField()),
                ('sorted_option', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('mid', models.OneToOneField(db_column='mid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='option_select.Movie')),
                ('rating', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('gid', models.OneToOneField(db_column='gid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='option_select.Genre')),
            ],
            options={
                'db_table': 'movie_genre',
                'managed': False,
            },
        ),
    ]
